environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #platform: Win32
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #platform: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: Win64

cache:
  - c:/Users/appveyor/.sw -> appveyor.yml

configuration:
  - Release

# for curl
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

before_build:
  - curl -fsS -L -o dl.zip https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-windows-client.zip
  - 7z x dl.zip
  - set PATH=%PATH%;%cd%

build_script:
  - sw -platform %platform% -static build -time-limit 45m

artifacts:
  - path: sw.zip
    name: sw-$(APPVEYOR_BUILD_VERSION)

after_build:
  - 7z a sw.zip %APPVEYOR_BUILD_FOLDER%\.sw\out\**\*.exe
  #- 7z a sw.zip %APPVEYOR_BUILD_FOLDER%\.sw\windows_*_msvc_*_static_Release\*.exe
#  - ps: Get-ChildItem .sw/windows_*_msvc_*_static_Release_*/*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName sw-$(APPVEYOR_BUILD_VERSION) }
